// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const FALLBACK_SUPABASE_URL = "https://ulbmusodwyjjicnginat.supabase.co";
const FALLBACK_SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVsYm11c29kd3lqamljbmdpbmF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg5NTk5MjksImV4cCI6MjA4NDUzNTkyOX0.rNk1jPePfro_IGQ3u2I_48bgDC1wSwYivTDkl3N-5Ww";

const normalizeEnvValue = (value: string | undefined): string => {
  return (value ?? "").trim().replace(/^['"]|['"]$/g, "");
};

const isValidAbsoluteHttpUrl = (value: string): boolean => {
  try {
    const parsed = new URL(value);
    return parsed.protocol === "https:" || parsed.protocol === "http:";
  } catch {
    return false;
  }
};

const envUrl = normalizeEnvValue(import.meta.env.VITE_SUPABASE_URL);
const envKey = normalizeEnvValue(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY);

const SUPABASE_URL = isValidAbsoluteHttpUrl(envUrl) ? envUrl : FALLBACK_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = envKey || FALLBACK_SUPABASE_PUBLISHABLE_KEY;

if (!isValidAbsoluteHttpUrl(envUrl) || !envKey) {
  console.warn(
    "[supabase] Invalid or missing Supabase env config. Using built-in fallback values."
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

export const resolvedSupabaseUrl = SUPABASE_URL;
